import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Provider } from './providers'

const inter = Inter({
  style: ['normal'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-dvh min-h-dvh w-dvw min-w-dvw bg-zinc-950`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
